[build]
  command = "npm run build"
  publish = "."

[template.environment]
  AXIE_API_KEY = "Enter your Axie API key"

[context.production.environment]
  NODE_ENV = "production"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 